"""
verify_backend_source_integrity.py
===================================
Validates that all bill-core backend copies are consistent with the canonical source.

Usage:
    python verify_backend_source_integrity.py           # summary report
    python verify_backend_source_integrity.py --fail    # exit 1 on any mismatch

Exit codes:
    0  All generated/deployed copies match canonical, or only expected files found
    1  A deployable copy differs from canonical (--fail mode), or canonical missing
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Root of the workspace (one level above bill-core)
WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

# Canonical source — the only file that should be hand-edited
CANONICAL_PATH = Path(__file__).resolve().parent / "main.py"

# Search roots to scan (excludes .venv / venv / site-packages automatically)
SEARCH_ROOTS: list[Path] = [
    WORKSPACE_ROOT / "bill-core",
    WORKSPACE_ROOT / "jarvis-platform" / "apps" / "bill-core",
]

# Directories whose names cause the scan to skip an entire subtree
SKIP_DIR_NAMES: set[str] = {
    ".venv", "venv", "env", "site-packages", "__pycache__",
    "node_modules", ".git",
}

# Directories that are **generated by the build script** — mismatches here
# are advisory (warn) not fatal, because they will be regenerated on next build.
GENERATED_ROOTS: set[str] = {
    "bill-core-deploy-clean",
}

# Classification type
FileClass = Literal["canonical", "generated_copy", "stale_generated_copy", "unknown_dangerous_copy"]


@dataclass
class FileReport:
    path: Path
    classification: FileClass
    line_count: int
    hash: str
    matches_canonical: bool
    note: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def line_count(path: Path) -> int:
    try:
        return sum(1 for _ in open(path, encoding="utf-8", errors="replace"))
    except OSError:
        return -1


def is_junction_or_symlink(path: Path) -> bool:
    """Return True if path is a Windows junction or a symlink."""
    try:
        return path.is_symlink() or (
            os.path.isdir(path) and bool(os.stat(path).st_reparse_tag)
            if hasattr(os.stat(path), "st_reparse_tag") else False
        )
    except (AttributeError, OSError):
        # Fallback: check via GetFinalPathNameByHandle is not available here;
        # use os.stat with follow_symlinks=False on Windows
        try:
            return path.stat().st_ino != path.stat(follow_symlinks=False).st_ino
        except (AttributeError, OSError):
            return False


def classify(path: Path, canonical_hash: str) -> FileClass:
    """Classify a main.py found during scan."""
    if path.resolve() == CANONICAL_PATH.resolve():
        return "canonical"

    # Check if any ancestor directory is a known generated root
    for part in path.parts:
        if part in GENERATED_ROOTS:
            file_hash = sha256_file(path)
            if file_hash == canonical_hash:
                return "generated_copy"
            else:
                return "stale_generated_copy"

    # Unknown location — treat as potentially dangerous
    file_hash = sha256_file(path)
    if file_hash == canonical_hash:
        # Same content but unknown location — informational
        return "generated_copy"
    return "unknown_dangerous_copy"


def scan_for_main_py(roots: list[Path], skip_names: set[str]) -> list[Path]:
    """Walk roots and collect all main.py files, skipping unwanted subtrees."""
    found: list[Path] = []

    for root in roots:
        if not root.exists():
            continue

        # If root is a junction/symlink that points to another scan root, skip
        # to avoid double-counting. We detect this by resolving the path.
        resolved = root.resolve()

        for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
            dir_path = Path(dirpath)

            # Prune unwanted directories in-place
            dirnames[:] = [
                d for d in dirnames
                if d not in skip_names
            ]

            if "main.py" in filenames:
                candidate = dir_path / "main.py"
                # Resolve to avoid counting junctions twice
                if candidate.resolve() not in {p.resolve() for p in found}:
                    found.append(candidate)

    return found


# ---------------------------------------------------------------------------
# Main verification logic
# ---------------------------------------------------------------------------

def run_verification(fail_on_mismatch: bool = False) -> int:
    """Run the integrity check and return exit code."""

    if not CANONICAL_PATH.exists():
        print(f"FATAL: Canonical source not found: {CANONICAL_PATH}")
        return 1

    canonical_hash = sha256_file(CANONICAL_PATH)
    canonical_lines = line_count(CANONICAL_PATH)

    print("=" * 70)
    print("Bill Core Backend Source Integrity Check")
    print("=" * 70)
    print(f"Canonical:  {CANONICAL_PATH}")
    print(f"  SHA-256:  {canonical_hash}")
    print(f"  Lines:    {canonical_lines:,}")
    print()

    found_paths = scan_for_main_py(SEARCH_ROOTS, SKIP_DIR_NAMES)

    reports: list[FileReport] = []
    for path in sorted(found_paths):
        file_hash = sha256_file(path)
        classification = classify(path, canonical_hash)
        matches = (file_hash == canonical_hash)
        lines = line_count(path)

        note = ""
        if classification == "stale_generated_copy":
            note = "WARN: generated copy differs from canonical — will be overwritten on next build"
        elif classification == "unknown_dangerous_copy":
            note = "DANGER: unknown copy differs from canonical — manual drift risk"

        reports.append(FileReport(
            path=path,
            classification=classification,
            line_count=lines,
            hash=file_hash,
            matches_canonical=matches,
            note=note,
        ))

    # Print report
    for r in reports:
        status = "OK" if r.matches_canonical else "MISMATCH"
        rel = r.path.relative_to(WORKSPACE_ROOT) if r.path.is_relative_to(WORKSPACE_ROOT) else r.path
        print(f"[{status}] {rel}")
        print(f"       classification : {r.classification}")
        print(f"       lines          : {r.line_count:,}")
        print(f"       sha256         : {r.hash}")
        if r.note:
            print(f"       {r.note}")
        print()

    # Summary
    dangerous = [r for r in reports if r.classification == "unknown_dangerous_copy"]
    stale = [r for r in reports if r.classification == "stale_generated_copy"]
    ok_count = sum(1 for r in reports if r.matches_canonical)

    print("=" * 70)
    print("Summary")
    print("=" * 70)
    print(f"  Files scanned    : {len(reports)}")
    print(f"  Match canonical  : {ok_count}")
    print(f"  Stale generated  : {len(stale)}  (will fix on next build)")
    print(f"  Dangerous copies : {len(dangerous)}")

    if not dangerous and not stale:
        print("\nRESULT: PASS — all copies are consistent with canonical source.")
    elif stale and not dangerous:
        print("\nRESULT: WARN — stale generated copies present (run build_eb_zip.py to sync).")
    else:
        print("\nRESULT: FAIL — unknown dangerous copies found that differ from canonical.")
        for r in dangerous:
            print(f"  !! {r.path}")

    print()

    if fail_on_mismatch and dangerous:
        return 1
    if fail_on_mismatch and stale:
        # Stale generated copies are warnings only — build will overwrite them
        return 0
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Verify bill-core backend source integrity against canonical main.py"
    )
    parser.add_argument(
        "--fail",
        action="store_true",
        help="Exit with code 1 if any unknown dangerous copy differs from canonical",
    )
    args = parser.parse_args()

    exit_code = run_verification(fail_on_mismatch=args.fail)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
